name: Windows build

on:
  push:
    branches:
    - dev
    - master
    - release
  pull_request:
    branches:
    - dev

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version:
        - 12.x
        - 13.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm test

      env:
        CI: true
